AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Despliegue de la aplicación (Frontend, API, BBDD) usando Docker Compose
  en una EC2 t3.micro. La contraseña está en el repo.

Parameters:
  MyKeyName:
    Description: Nombre de tu Key Pair (.pem) existente para acceder por SSH
    Type: AWS::EC2::KeyPair::KeyName
  MyHomeIP:
    Description: Tu IP de casa (para acceso SSH). Añade /32 al final.
    Type: String
    Default: '88.24.94.142/32' 
  RepoUrl:
    Description: URL del repositorio de GitHub (con la contraseña en el docker-compose.yml).
    Type: String
    Default: https://github.com/Carlossr2401/EntregaCN-API.git
  LatestAmiId:
    Description: ID de la AMI de Amazon Linux 2023.
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite SSH (desde casa) y HTTP (desde todos)
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyHomeIP
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref MyKeyName
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: Docker-Compose-Server
          
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          
          # 1. Instalar dependencias 
          dnf update -y
          dnf install git wget docker -y
          
          # 2. Iniciar Docker
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ec2-user
          
          # 3. Instalar plugins de Docker (Compose y Buildx)
          mkdir -p /usr/local/lib/docker/cli-plugins
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/lib/docker/cli-plugins/docker-compose
          wget https://github.com/docker/buildx/releases/download/v0.17.1/buildx-v0.17.1.linux-amd64 -O /usr/local/lib/docker/cli-plugins/docker-buildx
          chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          chmod +x /usr/local/lib/docker/cli-plugins/docker-buildx
          
          # 4. Ejecutar como 'ec2-user'
          su - ec2-user -c "
            # 5. Clonar el repositorio
            git clone ${RepoUrl} /home/ec2-user/app
            cd /home/ec2-user/app
            
            # 6. Limpiar el docker-compose.yml
            sed -i '/^version:/d' docker-compose.yml
            sed -i 's/\"8080:80\"/\"80:80\"/' docker-compose.yml
            
            # 7. ¡Lanzar el stack! (Sin secretos)
            docker compose up --build -d
          "

Outputs:
  PublicIP:
    Description: IP Pública de la instancia
    Value: !GetAtt MyEC2Instance.PublicIp
  PublicURL:
    Description: URL para acceder a la aplicación
    Value: !Sub 'http://${MyEC2Instance.PublicDnsName}'