AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Despliegue seguro de la aplicación (Frontend, API, BBDD) usando Docker Compose
  en una EC2 t3.micro, con secretos gestionados por AWS Secrets Manager.

Parameters:
  MyKeyName:
    Description: Nombre de tu Key Pair (.pem) existente para acceder por SSH
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Debe ser el nombre de un Key Pair existente en EC2.

  MyHomeIP:
    Description: Tu IP de casa (para acceso SSH). Añade /32 al final.
    Type: String
    Default: '88.24.94.142/32' # <-- ¡Esto es seguro!

  RepoUrl:
    Description: URL del repositorio de GitHub (que ya no tiene secretos).
    Type: String
    Default: https://github.com/Carlossr2401/EntregaCN-API.git

  SecretName:
    Description: El nombre del secreto en AWS Secrets Manager (ej. grades-app/db-password)
    Type: String
    Default: 'grades-app/db-password'

  LatestAmiId:
    Description: ID de la AMI de Amazon Linux 2023.
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'

Resources:
  # 1. ROL DE IAM (Permisos para la EC2)
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowReadSecrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                # Limita el permiso solo al secreto que creamos
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}-*'

  # 2. PERFIL DE INSTANCIA (Conecta el Rol a la EC2)
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  # 3. GRUPO DE SEGURIDAD
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite SSH (desde casa) y HTTP (desde todos)
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyHomeIP # <-- Seguro
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # 4. INSTANCIA EC2
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref MyKeyName
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      IamInstanceProfile: !Ref InstanceProfile # <-- Asigna el Rol de IAM
      Tags:
        - Key: Name
          Value: Docker-Compose-Server
          
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          
          # 1. Instalar dependencias
          dnf update -y
          dnf install git wget docker -y
          
          # 2. Iniciar Docker
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ec2-user
          
          # 3. Instalar plugins de Docker (Compose y Buildx)
          mkdir -p /usr/local/lib/docker/cli-plugins
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/lib/docker/cli-plugins/docker-compose
          wget https://github.com/docker/buildx/releases/download/v0.17.1/buildx-v0.17.1.linux-amd64 -O /usr/local/lib/docker/cli-plugins/docker-buildx
          chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          chmod +x /usr/local/lib/docker/cli-plugins/docker-buildx
          
          # 4. Instalar AWS CLI (para obtener el secreto)
          dnf install aws-cli -y

          # 5. Ejecutar como 'ec2-user'
          su - ec2-user -c "
            # 6. Clonar el repositorio
            git clone ${RepoUrl} /home/ec2-user/app
            cd /home/ec2-user/app
            
            # 7. (Opcional) Limpiar el docker-compose.yml
            sed -i '/^version:/d' docker-compose.yml
            sed -i 's/\"8080:80\"/\"80:80\"/' docker-compose.yml
            
            # 8. ¡OBTENER EL SECRETO!
            #    Obtiene el secreto y lo exporta como variable de entorno
            export DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id ${SecretName} --query SecretString --output text | jq -r .DB_PASSWORD)

            # 9. ¡Lanzar el stack!
            #    Docker Compose usará la variable DB_PASSWORD
            docker compose up --build -d
          "

Outputs:
  PublicIP:
    Description: IP Pública de la instancia
    Value: !GetAtt MyEC2Instance.PublicIp
  PublicURL:
    Description: URL para acceder a la aplicación
    Value: !Sub 'http://${MyEC2Instance.PublicDnsName}'