AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Stack de REST API + DynamoDB con 5 Lambdas externas.
  REQUIERE métodos OPTIONS manuales para CORS. [CORREGIDO]

# -------------------------------------------------------------------
# 1. Parámetros (5 Lambdas)
# -------------------------------------------------------------------
Parameters:
  CreateNoteLambdaArn:
    Type: String
    Description: El ARN de la función Lambda (creada manually) para POST /notas
  GetNoteByIdLambdaArn:
    Type: String
    Description: El ARN de la función Lambda (creada manually) para GET /notas/{noteId}
  GetAllNotesLambdaArn:
    Type: String
    Description: El ARN de la función Lambda (creada manually) para GET /notas (traer todo)
  UpdateNoteLambdaArn:
    Type: String
    Description: El ARN de la función Lambda (creada manually) para PUT /notas/{noteId}
  DeleteNoteLambdaArn:
    Type: String
    Description: El ARN de la función Lambda (creada manually) para DELETE /notas/{noteId}

# -------------------------------------------------------------------
# 2. Base de Datos
# -------------------------------------------------------------------
Resources:
  NotasTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NotasDeClase
      AttributeDefinitions:
        - AttributeName: NoteID
          AttributeType: S
        - AttributeName: AlumnoNombre
          AttributeType: S
      KeySchema:
        - AttributeName: NoteID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: AlumnoIndex
          KeySchema:
            - AttributeName: AlumnoNombre
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # -------------------------------------------------------------------
  # 3. API Gateway (REST API)
  # -------------------------------------------------------------------
  NotesRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: NotasApi-REST
      Description: API REST para Notas de Clase
      EndpointConfiguration:
        Types:
          - REGIONAL

  # -------------------------------------------------------------------
  # 4. Recursos de la API (Rutas)
  # -------------------------------------------------------------------
  NotasResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref NotesRestApi
      ParentId: !GetAtt NotesRestApi.RootResourceId
      PathPart: notas

  NotaResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref NotesRestApi
      ParentId: !Ref NotasResource
      PathPart: "{noteId}"

  # -------------------------------------------------------------------
  # 5. Métodos de Integración (Conexión a Lambdas)
  # -------------------------------------------------------------------

  # --- POST /notas ---
  PostNotasMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref NotesRestApi
      ResourceId: !Ref NotasResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateNoteLambdaArn}/invocations"

  # --- GET /notas ---
  GetAllNotesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref NotesRestApi
      ResourceId: !Ref NotasResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST 
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetAllNotesLambdaArn}/invocations"
        
  # --- GET /notas/{noteId} ---
  GetNoteByIdMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref NotesRestApi
      ResourceId: !Ref NotaResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetNoteByIdLambdaArn}/invocations"

  # --- PUT /notas/{noteId} ---
  PutNoteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref NotesRestApi
      ResourceId: !Ref NotaResource
      HttpMethod: PUT
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateNoteLambdaArn}/invocations"

  # --- DELETE /notas/{noteId} ---
  DeleteNoteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref NotesRestApi
      ResourceId: !Ref NotaResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteNoteLambdaArn}/invocations"

  # -------------------------------------------------------------------
  # 6. Métodos MOCK para CORS (¡OBLIGATORIO en REST API!)
  # -------------------------------------------------------------------

  # --- OPTIONS /notas ---
  OptionsNotasMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref NotesRestApi
      ResourceId: !Ref NotasResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
            
  # --- OPTIONS /notas/{noteId} ---
  OptionsNotaMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref NotesRestApi
      ResourceId: !Ref NotaResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # -------------------------------------------------------------------
  # 7. Despliegue de la API
  # -------------------------------------------------------------------
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PostNotasMethod
      - GetAllNotesMethod
      - GetNoteByIdMethod
      - PutNoteMethod
      - DeleteNoteMethod
      - OptionsNotasMethod
      - OptionsNotaMethod
    Properties:
      RestApiId: !Ref NotesRestApi

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref NotesRestApi
      DeploymentId: !Ref ApiDeployment
      StageName: prod

  # -------------------------------------------------------------------
  # 8. Permisos
  # -------------------------------------------------------------------
  LambdaPermissionCreate:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateNoteLambdaArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${NotesRestApi}/*/POST/notas"
      
  LambdaPermissionGetById:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetNoteByIdLambdaArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${NotesRestApi}/*/GET/notas/{noteId}"
      
  LambdaPermissionGetAllNotes:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetAllNotesLambdaArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${NotesRestApi}/*/GET/notas"
      
  LambdaPermissionUpdate:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UpdateNoteLambdaArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${NotesRestApi}/*/PUT/notas/{noteId}"
      
  LambdaPermissionDelete:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DeleteNoteLambdaArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${NotesRestApi}/*/DELETE/notas/{noteId}"

Outputs:
  NotasApiEndpoint:
    Description: "URL del endpoint de la API de Notas (REST API)"
    Value: !Sub "https://${NotesRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  NotasTableName:
    Description: "Nombre de la tabla DynamoDB de Notas"
    Value: !Ref NotasTable